python submitit_train.py \
    --dataset=bbbc021 \
    --batch_size=32 \
    --accum_iter=1 \
    --eval_frequency=25 \
    --epochs=200 \
    --class_drop_prob=0.2 \
    --cfg_scale=0.2 \
    --compute_fid \
    --ode_method heun2 \
    --ode_options '{"nfe": 50}' \
    --use_ema \
    --edm_schedule \
    --skewed_timesteps \
    --fid_samples=5120 \
    --job_dir=/path/to/your/outputs/ \
    --shared_dir=/path/to/your/shared/ \
    --use_initial=2 \
    --noise_level=1.0 \
    --noise_prob=0.5 \
    --save_fid_samples
